sudo: required
language: php
dist: trusty

php:
  - 7.2.7

node_js:
  - 8

services:
  - mysql
  - redis-server

before_install:
  - bash .travis.install-mysql-5.7.sh
  - mysql -e 'CREATE DATABASE test_db;'
  - curl -sSfL -o ~/.phpenv/versions/7.2.7/bin/phpunit https://phar.phpunit.de/phpunit-6.0.phar

install:
  - composer install --no-interaction
  - yarn run setup

before_script:
  - mv .env.travis .env
  - php artisan key:generate
  - php artisan migrate
  - php artisan db:seed --class=TestSeeder

script:
  - phpunit --filter=Api
  - yarn run test
  - yarn run lint

after_failure:
  - cat storage/logs/laravel.log | grep testing.ERROR
