ARG TAG

FROM registry.bethink.tech/platform-app-php-dusk:${TAG} as source_image

FROM nginx:1.14.0-alpine
COPY --from=source_image /www/current/public /www/current/public/
COPY --from=source_image /www/current/resources/views/errors /www/current/resources/views/errors/

