version: '3'

services:

  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile.dev.php
    env_file:
      - .env
      - .env.testing
    environment:
      # Required for ngrok
      - P24_STATUS_URL
    ports:
      - "9000:9000"
    volumes:
      - ${LOCAL_CODE_PATH}:${CONTAINER_CODE_PATH}
    working_dir: ${CONTAINER_CODE_PATH}/wnl-platform

  nginx:
    container_name: nginx
    image: nginx:1.15.0-alpine
    ports:
      - "80:80"
      # Required for ngrok
      - "0.0.0.0:4040:4040"
    volumes:
      - ${LOCAL_DEV_PATH}/nginx/:/etc/nginx/conf.d:ro
      - ${LOCAL_CODE_PATH}:${CONTAINER_CODE_PATH}

  selenium:
    container_name: selenium
    image: selenium/standalone-chrome-debug
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
      - "5900:5900"
