<?php

return [
	'resources' => [
		'courses'             => 'courses',
		'groups'              => 'groups',
		'lessons'             => 'lessons',
		'screens'             => 'screens',
		'sections'            => 'sections',
		'users'               => 'users',
		'user-profile'        => 'profile',
		'user-address'        => 'address',
		'user-billing-data'   => 'billing',
		'user-settings'       => 'settings',
		'user-avatar'         => 'avatar',
		'user-password'       => 'password',
		'editions'            => 'editions',
		'orders'              => 'orders',
		'tags'                => 'tags',
		'questions'           => 'questions',
		'answers'             => 'answers',
		'lesson-availability' => 'lesson_availability',
		'user-progress'       => 'user_progress',
		'slideshows'          => 'slideshows',
		'quiz-questions'      => 'quiz_questions',
		'quiz-answers'        => 'quiz_answers',
		'quiz-sets'           => 'quiz_sets',
		'slides'              => 'slides',
		'presentables'        => 'presentables',
	],
];
