<?php

return [
	'resources' => [
		'courses'            => 'courses',
		'groups'             => 'groups',
		'lessons'            => 'lessons',
		'user-lesson'        => 'user_lesson',
		'screens'            => 'screens',
		'sections'           => 'sections',
		'users'              => 'users',
		'user-profile'       => 'profile',
		'user-address'       => 'address',
		'user-billing-data'  => 'billing',
		'user-settings'      => 'settings',
		'user-avatar'        => 'avatar',
		'user-password'      => 'password',
		'user-notifications' => 'notifications',
		'user-reactions'     => 'reactions',
		'user-state'         => 'state',
		'user-quiz-results'  => 'quiz_results',
		'user-collections'   => 'user_collections',
		'editions'           => 'editions',
		'orders'             => 'orders',
		'tags'               => 'tags',
		'qna-questions'      => 'qna_questions',
		'qna-answers'        => 'qna_answers',
		'user-progress'      => 'user_progress',
		'slideshows'         => 'slideshows',
		'quiz-questions'     => 'quiz_questions',
		'quiz-sets'          => 'quiz_sets',
		'quiz-stats'         => 'quiz_stats',
		'slides'             => 'slides',
		'presentables'       => 'presentables',
		'comments'           => 'comments',
		'chat-rooms'         => 'chat_rooms',
		'chat-messages'      => 'chat_messages',
		'reactions'          => 'reactions',
		'reactables'         => 'reactables',
		'categories'         => 'categories',
		'slideshow-builder'  => 'slideshow_builder',
		'profiles'           => 'user_profiles',
		'user-plan'          => 'user_plan',
		'tasks'              => 'tasks',
		'pages'              => 'pages',
		'user-forget'        => 'user_forget',
		'invoices'           => 'invoices',
		'certificates'       => 'certificates',
		'annotations'        => 'annotations',
		'user-personal-data'      => 'personal_data'
	],
];
